version: '3.8'

services:
  mongo:
    image: mongo
    container_name: docs-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: docs-server
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/docsApp
    depends_on:
      - mongo

volumes:
  mongo-data:
