# Use Node LTS
FROM node:18

# Create app directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the app code
COPY . .

# Expose port
EXPOSE 3001

# Start the server
CMD ["node", "index.js"]
